--------------------------------------------------------
--  ÉtÉ@ÉCÉãÇçÏê¨ÇµÇ‹ÇµÇΩ - ìyójì˙-3åé-17-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_SYSTEM_INFO
--------------------------------------------------------

  CREATE TABLE "CSC_USER"."T_SYSTEM_INFO" 
   (	"SYS_BUSINESS_DAY" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CSC_USER.T_SYSTEM_INFO
SET DEFINE OFF;
Insert into CSC_USER.T_SYSTEM_INFO (SYS_BUSINESS_DAY) values ('20171217');
--------------------------------------------------------
--  DDL for Index T_SYSTEM_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSC_USER"."T_SYSTEM_INFO_PK" ON "CSC_USER"."T_SYSTEM_INFO" ("SYS_BUSINESS_DAY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table T_SYSTEM_INFO
--------------------------------------------------------

  ALTER TABLE "CSC_USER"."T_SYSTEM_INFO" ADD CONSTRAINT "T_SYSTEM_INFO_PK" PRIMARY KEY ("SYS_BUSINESS_DAY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSC_USER"."T_SYSTEM_INFO" MODIFY ("SYS_BUSINESS_DAY" NOT NULL ENABLE);
