--------------------------------------------------------
--  ÉtÉ@ÉCÉãÇçÏê¨ÇµÇ‹ÇµÇΩ - ìyójì˙-3åé-17-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table M_PRODUCT
--------------------------------------------------------

  CREATE TABLE "CSC_USER"."M_PRODUCT" 
   (	"PRODUCT_CD" VARCHAR2(6 BYTE), 
	"UNIT_PRICE_START_YMD" VARCHAR2(8 BYTE), 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"SALE_UNIT_PRICE" NUMBER(8,0), 
	"COST_UNIT_PRICE" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index M_PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSC_USER"."M_PRODUCT_PK" ON "CSC_USER"."M_PRODUCT" ("PRODUCT_CD", "UNIT_PRICE_START_YMD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table M_PRODUCT
--------------------------------------------------------

  ALTER TABLE "CSC_USER"."M_PRODUCT" ADD CONSTRAINT "M_PRODUCT_PK" PRIMARY KEY ("PRODUCT_CD", "UNIT_PRICE_START_YMD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSC_USER"."M_PRODUCT" MODIFY ("UNIT_PRICE_START_YMD" NOT NULL ENABLE);
  ALTER TABLE "CSC_USER"."M_PRODUCT" MODIFY ("PRODUCT_CD" NOT NULL ENABLE);
