--------------------------------------------------------
--  ÉtÉ@ÉCÉãÇçÏê¨ÇµÇ‹ÇµÇΩ - ìyójì˙-3åé-17-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_SALE
--------------------------------------------------------

  CREATE TABLE "CSC_USER"."T_SALE" 
   (	"VOUCHER_NO" VARCHAR2(22 BYTE), 
	"SHOP_CD" VARCHAR2(6 BYTE), 
	"SALE_YMD" VARCHAR2(8 BYTE), 
	"SALE_AMOUNT" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_SALE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSC_USER"."T_SALE_PK" ON "CSC_USER"."T_SALE" ("VOUCHER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table T_SALE
--------------------------------------------------------

  ALTER TABLE "CSC_USER"."T_SALE" ADD CONSTRAINT "T_SALE_PK" PRIMARY KEY ("VOUCHER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSC_USER"."T_SALE" MODIFY ("VOUCHER_NO" NOT NULL ENABLE);
