--------------------------------------------------------
--  ÉtÉ@ÉCÉãÇçÏê¨ÇµÇ‹ÇµÇΩ - ìyójì˙-3åé-17-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_SALE_TRAN
--------------------------------------------------------

  CREATE TABLE "CSC_USER"."T_SALE_TRAN" 
   (	"SEQ_T_SALE_TRAN" NUMBER(12,0), 
	"INCLUSION_YMD" VARCHAR2(8 BYTE), 
	"VOUCHER_NO" VARCHAR2(22 BYTE), 
	"PRODUCT_CD" VARCHAR2(6 BYTE), 
	"SALES" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_SALE_TRAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSC_USER"."T_SALE_TRAN_PK" ON "CSC_USER"."T_SALE_TRAN" ("SEQ_T_SALE_TRAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table T_SALE_TRAN
--------------------------------------------------------

  ALTER TABLE "CSC_USER"."T_SALE_TRAN" ADD CONSTRAINT "T_SALE_TRAN_PK" PRIMARY KEY ("SEQ_T_SALE_TRAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSC_USER"."T_SALE_TRAN" MODIFY ("SEQ_T_SALE_TRAN" NOT NULL ENABLE);
